[theme]
base = "light"
primaryColor = "#86B264"
backgroundColor = "white"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#333333"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "viewer"
